[project]
name = "eulervoid.com"
revision = "1.0"

[providers.age]
uri = "age://secrets.age"

[profiles.default]
PROFILE_NAME = { description = "Name", providers = ["age"] }
PROFILE_STREET_ADDRESS = { description = "Street", providers = ["age"] }
PROFILE_POSTAL_CODE = { description = "Postal Code", providers = ["age"] }
PROFILE_CITY = { description = "City", default = "Berlin", providers = ["age"] }
PROFILE_COUNTRY = { description = "Country", default = "Germany", providers = ["age"] }
PROFILE_VAT_ID = { description = "VAT ID", providers = ["age"] }
PROFILE_EMAIL = { description = "Email", providers = ["age"] }
