/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImprintRouteImport } from './routes/imprint'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as DataResumeRouteImport } from './routes/data/resume'
import { Route as DataWorkRouteImport } from './routes/data/work'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprintRoute = ImprintRouteImport.update({
  id: '/imprint',
  path: '/imprint',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DataResumeRoute = DataResumeRouteImport.update({
  id: '/data/resume',
  path: '/data/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const DataWorkRoute = DataWorkRouteImport.update({
  id: '/data/work',
  path: '/data/work',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/timeline': typeof TimelineRoute
  '/data/resume': typeof DataResumeRoute
  '/data/work': typeof DataWorkRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/timeline': typeof TimelineRoute
  '/data/resume': typeof DataResumeRoute
  '/data/work': typeof DataWorkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/imprint': typeof ImprintRoute
  '/privacy': typeof PrivacyRoute
  '/timeline': typeof TimelineRoute
  '/data/resume': typeof DataResumeRoute
  '/data/work': typeof DataWorkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/imprint' | '/privacy' | '/timeline' | '/data/resume' | '/data/work'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/imprint' | '/privacy' | '/timeline' | '/data/resume' | '/data/work'
  id:
    | '__root__'
    | '/'
    | '/imprint'
    | '/privacy'
    | '/timeline'
    | '/data/resume'
    | '/data/work'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImprintRoute: typeof ImprintRoute
  PrivacyRoute: typeof PrivacyRoute
  TimelineRoute: typeof TimelineRoute
  DataResumeRoute: typeof DataResumeRoute
  DataWorkRoute: typeof DataWorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprint': {
      id: '/imprint'
      path: '/imprint'
      fullPath: '/imprint'
      preLoaderRoute: typeof ImprintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/resume': {
      id: '/data/resume'
      path: '/data/resume'
      fullPath: '/data/resume'
      preLoaderRoute: typeof DataResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/work': {
      id: '/data/work'
      path: '/data/work'
      fullPath: '/data/work'
      preLoaderRoute: typeof DataWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImprintRoute: ImprintRoute,
  PrivacyRoute: PrivacyRoute,
  TimelineRoute: TimelineRoute,
  DataResumeRoute: DataResumeRoute,
  DataWorkRoute: DataWorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
